### ISSUE TITLE
Create the MVP

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/rest-client#1]
# Idea

This rest client will support the basic rest functionalities like GET, PUT, UPDATE, DELETE and so on. I will be made available as docker image to easily pull and setup on any machine. The like the idea of having a small web-based client instead of a large desktop app (even though tools like Postman will have greater functionality).

# Stack

The app is going to be based on .NET 7 and will be written in C#.

# TODOs

- [ ] Create the basic project
- [ ] Create the MVP (web app with support for basic rest operations)
- [ ] Create a Dockerfile or image

# Additional features

This is a collection of additional features that may (or may not) be added to the app.

- [ ] Users should be able to add requests to a project, name projects and store them (SQL database + connection?)
